### ISSUE TITLE
Possible break on Godot 3.2.4.rc3?

### ISSUE THREAD

**Issue by coppolaemilio** [godot-extended-libraries/godot-plugin-refresher#13]
First of all, thanks for the plugin. A life saver!

Since the latest Godot build 3.2.4.rc3 the plugin-refresher can't find any my plugins. 
![image](https://user-images.githubusercontent.com/2206700/108980020-88a55380-768b-11eb-88d5-1014f8459ced.png)

I tried to fix the plugin-refresher myself but I can't really find where it is going wrong.

I'm completely lost so I'm creating this issue just in case you know what might have changed :(

**Comment by willnationsdev** [comment]
oh, huh. No, this is news to me. I suppose I'll have to look into it further. Thanks for the heads-up!

**Comment by willnationsdev** [comment]
@coppolaemilio I think I found the issue in the engine code. If you wouldn't mind, do you think you could open a bug report in godotengine/godot since you're the one actually experiencing it?

The problem appears to be (to me) that an attempt was made to simplify the logic related to identifying what a plugin inherently *was* (shifting away from a dependency on the .cfg file), but in the process they messed up the logic for identifying the existence of the addon. You can see in 3.2-stable, [here](https://github.com/godotengine/godot/blob/3.2.3-stable/editor/editor_node.cpp#L3148) where they fetch the config file and get its base dir:

    res://addons/godot-plugin-refresher/plugin.cfg -> res://adons/godot-plugin-refresher
    
...but then in the latest 3.2 [here](https://github.com/godotengine/godot/blob/3.2/editor/editor_node.cpp#L3230), they remove the config file path and use *just* the addon's subdirectory and try to get its base dir:

    godot-plugin-refresher -> ""

This then results in the addon never being found in any conceivable case, afaict.

**Comment by coppolaemilio** [comment]
Yeah, I'll create an issue on the Godot repo! Thanks for your looking into it!

**Comment by willnationsdev** [comment]
Then, since this isn't a problem with the addon's code, I'm gonna close this. Cheers!
