### ISSUE TITLE
Instructions are unclear about refresh button

### ISSUE THREAD

**Issue by nezvers** [godot-extended-libraries/godot-plugin-refresher#14]
There are no mentions of the location where is the refresh button. It was mentioned "in toolbar" which begs the question of what is the "toolbar". I thought it was above viewport where usually plugin buttons are located. After 10 minutes of searching for information, I accidentally looked in the corner, next to GLES2/ GLES3 menu, and found it there.

**Comment by willnationsdev** [comment]
That's interesting. I have never considered that it would be confusing since there are plenty of plugins that manipulate the main toolbar (e.g. anything that adds a new main screen), and it would be strange if a plugin that refreshes content presumably anywhere in the Editor were unable to refresh a plugins when the user isn't in the 2D or 3D viewport tabs (as would be the case if it only appeared in the viewport toolbar). With that said, I don't see any harm in adding a bit more specificity to the description.

**Comment by willnationsdev** [comment]
Closed by e41fc33a02541b0a2b013f030af5aa1358d84e1b.
