### ISSUE TITLE
Must be installed as godot-plugin-refresher

### ISSUE THREAD

**Issue by idbrii** [godot-extended-libraries/godot-plugin-refresher#27]
I installed to res://addons/plugin-refresher and the dropdown was empty. I noticed these errors in Output:

```
 res://addons/plugin-refresher/plugin_refresher_plugin.gd:69 - Invalid call. Nonexistent function 'update_items' in base 'HBoxContainer'.
 res://addons/plugin-refresher/plugin_refresher_plugin.gd:100 - Invalid call. Nonexistent function 'select_plugin' in base 'HBoxContainer'.
```

After debugging for a bit, I saw this warning:

```
 scene/resources/resource_format_text.cpp:157 - Couldn't load external resource: res://addons/godot-plugin-refresher/plugin_refresher.gd
```

I realized that the plugin required installing as "godot-plugin-refresher". Maybe this isn't unique to this plugin? (I'm new to godot.) Maybe would be nice to have install instructions?

**Comment by idbrii** [comment]
It's located at addons/godot-plugin-refresher within this repo, so of course I must use that same path when I put it in my project. I guess if anything godot should have better support for detecting incorrectly installed plugins.

Closing as invalid.

**Comment by willnationsdev** [comment]
Yeah, improving the addon/plugin architecture is definitely high on my list of things I want to work on in the source code. Unfortunately, there are a LOT of stakeholders involved all with different preferences for how each little aspect of the stuff should work, so the issues and proposals revolving around it usually takes a very long time to discuss and are slow to reach any sort of definitive conclusion as to the best way to solve things (and still hadn't come to a conclusion last I checked, around a year ago).

I have a highly upvoted proposal about it. Juan/Reduz has some "tree of nested Godot projects" proposal (I forget its name) that sounded intriguing.

Ultimately though, we need to have an official package manager, namespacing, and an official service for centralizing it all, similar to NuGet, assemblies/namespaces, and nuget.org for the .NET ecosystem.

I would guess that it'll be a LONG time before an official solution is built, just because manpower is hard to get (both diverse and strong skills AND knowledge necessary), and no actual (productive) work can be done until the community has come to a consensus on things.
